### PR TITLE
added some packaging options for rpm and aps

### PR DESCRIPTION
**Pull request by cburgard**
Some package definitions for archlinux (APS) and fedora (RPM) were added.

For this, I felt that I needed to refactor a few things in the CMakeLists.txt, but perhaps there is some room for improvement there.

### CODE REVIEW

**Comment by biojppm** [comment]
Thanks for the PR!

FWIW, in the limited time I've had in the last couple of months I've been working on having install targets dealt with in my c4Project.cmake (inside c4core). Let's keep this PR on hold until that comes in, as some parts of it will likely be useful.

**Comment by cburgard** [comment]
Do you have any timeline for this in mind already? I was hoping to have something working on the timescale of ~1 month.

**Comment by biojppm** [comment]
I can't provide a hard guarantee, but if I can it will be sooner than that.

**Comment by cburgard** [comment]
that would be great!

**Comment by biojppm** [comment]
@cburgard Have you tried the install target (added to master somewhere in December)? Does it work for you?

**Comment by biojppm** [comment]
@cburgard Again, thanks for the PR. I'm going to close it, but feel free to reopen if you want to go ahead with this.

**Pull request closed without merging**
