### PR TITLE
Refactor release CI

### PR DESCRIPTION
**Pull request by biojppm**
re #146

### CODE REVIEW

**Comment by biojppm** [comment]
@mithro @litghost I've added creation of python packages in the release github action. How do you want to proceed? Should these be submitted to PyPI from the action?

image

**Comment by mithro** [comment]
Yes, let's submit these to PyPi as part of the action.

You should create an "robot" account on PyPi and then send me the username. I'll give it ownership of the rapidyaml module.

**Comment by mithro** [comment]
jpmag should have an invite on PyPi now.

**Comment by biojppm** [comment]
@mithro can you also add `jpmag` to the pypitest repo?

**Comment by mithro** [comment]
@biojppm - Invite to the test.pypi.org sent!

**Pull request merged**
