### PR TITLE
Adds a unit test to parse 3 digits versions

### PR DESCRIPTION
**Pull request by ericcitaire**
See https://github.com/google/jsonnet/issues/1014

### CODE REVIEW

**Comment by biojppm** [comment]
tangentially related: #292

**Comment by biojppm** [comment]
@ericcitaire I force-pushed a fix to your commit, and elaborated the tests. I don't know what is the particular problem you are having (the linked bug does not provide any context and is unclear for me), but the tests now do a successful roundtrip of multi-dot version strings, both in YAML and JSON. If the CI passes, this should be evidence that the problem is neither in ryml's parsing nor emitting.

**Comment by biojppm** [comment]
Indeed the tests succeed (the 9 failures are unrelated). Merging now. Thanks!

**Comment by ericcitaire** [comment]
> @ericcitaire hard to see from [google/jsonnet#1014](https://github.com/google/jsonnet/issues/1014). Is it a duplicate of #292 (already fixed in master)?

Indeed, it seems to be a duplicate of #292. Sorry, I missed it.

So I guess [google/jsonnet](https://github.com/google/jsonnet) just have to rebuild with a recent version of rapidyaml.

Thanks !

**Pull request merged**
